CREATE DATABASE Facial

USE Facial

CREATE TABLE [dbo].[USER]
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	FULLNAME VARCHAR(255) NOT NULL,
	[ADDRESS] VARCHAR(255) NOT NULL,
	EMAILADDRESS VARCHAR(255) NOT NULL,
	PHONENUMBER VARCHAR(11) NOT NULL CHECK(LEN(PHONENUMBER) = 11),
	AGE INT NOT NULL,
	GENDER VARCHAR(50) NOT NULL,
	CIVILSTATUS VARCHAR(255) NOT NULL,
	GUARDIAN VARCHAR(255) NOT NULL,
	DATEOFBIRTH DATE NOT NULL,
	WORKSTATUS VARCHAR(255) NOT NULL,
	REFERENCENUMBER VARCHAR(255) NOT NULL,
	CONSTRAINT chk_email CHECK (EMAILADDRESS LIKE '%@%')
);

CREATE TABLE GENDER
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[TYPE] VARCHAR(255) NOT NULL
);

CREATE TABLE CIVILSTATUS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[STATUS] VARCHAR(255) NOT NULL
);

CREATE TABLE WORKSTATUS
(
	ID INT PRIMARY KEY IDENTITY(1,1),
	[STATUS] VARCHAR(255) NOT NULL
);

INSERT INTO GENDER VALUES('Male'), ('Female'), ('Prefer Not to Say')
SELECT * FROM GENDER

INSERT INTO CIVILSTATUS ([STATUS])
VALUES 
('Single'),
('Married'),
('Divorced'),
('Widowed');
SELECT * FROM CIVILSTATUS

INSERT INTO WORKSTATUS VALUES ('Student'), ('Employee'), ('Working Student')
SELECT * FROM WORKSTATUS